services:
  kuma-mieru:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kuma-mieru
    restart: unless-stopped
    ports:
      - "3883:3000"
    environment:
      - NODE_ENV=production
      - UPTIME_KUMA_BASE_URL=${UPTIME_KUMA_BASE_URL}
      - PAGE_ID=${PAGE_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
