services:
  kuma-mieru:
    image: ghcr.io/alice39s/kuma-mieru:main
    build:
      context: .
      args:
        NODE_ENV: production
        VERSION: ${VERSION:-dev}
        BUILD_DATE: ${BUILD_DATE:-unknown}
        VCS_REF: ${VCS_REF:-unknown}
      dockerfile: Dockerfile
    container_name: kuma-mieru
    restart: unless-stopped
    ports:
      - "3883:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next/cache
