name: Auto Update from Upstream

on:
  schedule:
    - cron: '30 1 * * *'  # 每天凌晨 1:30 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  auto-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check auto-update lock file
        id: check_lock
        run: |
          if [ -f "auto-update.lock" ]; then
            echo "Auto update is locked. Skipping..."
            echo "locked=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "locked=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Set up Git
        if: steps.check_lock.outputs.locked == 'false'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add upstream remote
        if: steps.check_lock.outputs.locked == 'false'
        run: |
          git remote add upstream https://github.com/Alice39s/kuma-mieru.git
          git remote -v
          
      - name: Fetch upstream
        if: steps.check_lock.outputs.locked == 'false'
        run: |
          git fetch upstream
          
      - name: Check for updates
        if: steps.check_lock.outputs.locked == 'false'
        id: check_updates
        run: |
          LOCAL=$(git rev-parse HEAD)
          UPSTREAM=$(git rev-parse upstream/main)
          if [ "$LOCAL" != "$UPSTREAM" ]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Merge upstream
        if: steps.check_lock.outputs.locked == 'false' && steps.check_updates.outputs.updates_available == 'true'
        run: |
          git merge upstream/main --no-edit
          
      - name: Push changes
        if: steps.check_lock.outputs.locked == 'false' && steps.check_updates.outputs.updates_available == 'true'
        run: |
          git push origin main 