name: Docker Build and Push

on:
  push:
    branches: ["main"]
    paths:
      - "package.json"
      - "Dockerfile"
      - ".github/workflows/docker-build.yml"
      - "docker-compose.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "package.json"
      - "Dockerfile"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package version
        id: package_version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.package_version.outputs.version }}
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=ref,event=pr
          labels: |
            org.opencontainers.image.title=Kuma Mieru
            org.opencontainers.image.description=A 3rd-party Uptime Kuma monitoring dashboard built on Next.js 15, TypeScript and Recharts.
            org.opencontainers.image.version=${{ steps.package_version.outputs.version }}
            org.opencontainers.image.licenses=MPL-2.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.package_version.outputs.version }}
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VCS_REF=${{ github.sha }}
            BUILD_MODE=true
